[versions]
commons-codec = "1.18.0"
commons-lang3 = "3.17.0"
equalsverifier = "4.0"
hamcrest = "3.0"
junit5 = "5.13.0"
kotlin-jvm = "2.1.21"
sonarqube-plugin = "6.2.0.5505"

[libraries]
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
equalsverifier = { group = "nl.jqno.equalsverifier", name = "equalsverifier", version.ref = "equalsverifier" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
sonarqube-plugin = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }
